export const EventEmitter = {
  userFound: 'user.found',
  categoryFound: 'category.found',
  jobFound: 'job.found',
  eventFound: 'event.found',
  workerPositionFound: 'worker.position.found',
  workerPositionNotFound: 'worker.position.not.found',
  workerPositionFoundAll: 'worker.position.found.all',
  workerPositionUpdated: 'worker.position.updated',
  workerPositionOneApprove: 'worker.position.one.approve',
  workerPositionIsExist: 'worker.position.exists',
  workerPositionCanceledIsExist: 'worker.position.Canceled',
  workerPositionJobAndEmit: 'worker.position.job.emit',
  workerPositionNotFoundOne: 'worker.position.not.found.error',
  geolocationCreated: 'geolocation.create',
  managerPrimaryValidate: 'manager.primary.validate',
  managerPrimaryFoundAll: 'manager.primary.All',
  checkCreateMany: 'check.create.many',
  checkAllFoundAll: 'check.all.found',
};
