export enum Section {
  ADMINISTRATION = 'Administración',
  ARCHIVES = 'Archivos',
  ARTIFACTS = 'Artefactos',
  AUDIOVISUAL = 'Audiovisual',
  BOOKS = 'Libros',
  CONSERVATION = 'Conservación',
  DOCUMENTS = 'Documentos',
  EXHIBITIONS = 'Exposiciones',
  HISTORICAL = 'Histórico',
  MANUSCRIPTS = 'Manuscritos',
  MAPS = 'Mapas',
  PHOTOGRAPHS = 'Fotografías',
  RARE_BOOKS = 'Libros Raros',
  RESEARCH = 'Investigación',
  SPECIAL_COLLECTIONS = 'Colecciones Especiales',
  OTHER = 'Otro',
}