export enum FundTitle {
  ARCHIVE = 'Archivo',
  COLLECTION = 'Colección',
  LIBRARY = 'Biblioteca',
  MUSEUM = 'Museo',
  GALLERY = 'Galería',
  PRIVATE_COLLECTION = 'Colección Privada',
  INSTITUTIONAL_COLLECTION = 'Colección Institucional',
  THEMATIC_COLLECTION = 'Colección Temática',
  HISTORICAL_COLLECTION = 'Colección Histórica',
  SPECIAL_COLLECTION = 'Colección Especial',
  RESEARCH_COLLECTION = 'Colección de Investigación',
  EDUCATIONAL_COLLECTION = 'Colección Educativa',
  OTHER = 'Otro',
}
