export enum ValueGrade {
  EXCEPTIONAL = 'Excepcional',
  HIGH = 'Alto',
  MEDIUM = 'Medio',
  LOW = 'Bajo',
  HISTORICAL = 'Histórico',
  CULTURAL = 'Cultural',
  SCIENTIFIC = 'Científico',
  ARTISTIC = 'Artístico',
  ARCHAEOLOGICAL = 'Arqueológico',
  DOCUMENTARY = 'Documental',
  EDUCATIONAL = 'Educativo',
  RESEARCH = 'Investigación',
  OTHER = 'Otro',
}
