export enum HeritageType {
  CULTURAL = 'Cultural',
  NATURAL = 'Natural',
  MIXED = 'Mixto',
  TANGIBLE = 'Tangible',
  INTANGIBLE = 'Intangible',
  MOVABLE = 'Mueble',
  IMMOVABLE = 'Inmueble',
  DOCUMENTARY = 'Documental',
  DIGITAL = 'Digital',
  INDUSTRIAL = 'Industrial',
  ARCHAEOLOGICAL = 'Arqueológico',
  UNDERWATER = 'Subacuático',
  WORLD = 'Mundial',
  NATIONAL = 'Nacional',
  LOCAL = 'Local',
  OTHER = 'Otro',
}
